"""
notes.py
--------
Auto-generates a structured markdown notes template for a CVE.
Great for CTFs, pentest practice, and keeping track of your progress.

Generated files are saved to a /notes folder in your project directory.

Usage (standalone):
    python notes.py CVE-2021-44228

Usage (from cli.py):
    from notes import generate_note
    generate_note(cve, recon_results, resource_results)
"""

import os
from datetime import datetime

# ── Notes folder ──────────────────────────────────────────────────────────────
NOTES_DIR = os.path.join(os.path.dirname(os.path.abspath(__file__)), "notes")


def ensure_notes_dir():
    """Creates the /notes folder if it doesn't exist."""
    if not os.path.exists(NOTES_DIR):
        os.makedirs(NOTES_DIR)


def get_note_path(cve_id: str) -> str:
    """Returns the file path for a CVE note."""
    filename = cve_id.upper().replace("-", "_") + ".md"
    return os.path.join(NOTES_DIR, filename)


def generate_note(
    cve:       dict,
    recon:     dict = None,
    resources: dict = None,
) -> str:
    """
    Generates a markdown notes template for a CVE and saves it to /notes.

    Args:
        cve (dict):       CVE data from fetcher.fetch_cve()
        recon (dict):     Recon results from recon.run_recon() — optional
        resources (dict): Resource results from resources.get_resources() — optional

    Returns:
        str: Full path to the saved notes file
    """
    ensure_notes_dir()

    cve_id    = cve["id"]
    now       = datetime.now().strftime("%Y-%m-%d %H:%M")
    note_path = get_note_path(cve_id)

    lines = []

    # ── Header ────────────────────────────────────────────────────────────────
    lines.append("# " + cve_id)
    lines.append("")
    lines.append("> Generated by CVE Scaffolder on " + now)
    lines.append("")
    lines.append("---")
    lines.append("")

    # ── CVE Overview ──────────────────────────────────────────────────────────
    lines.append("## Overview")
    lines.append("")
    lines.append("| Field       | Value |")
    lines.append("|-------------|-------|")
    lines.append("| **CVE ID**  | " + cve_id + " |")
    lines.append("| **Severity**| " + str(cve["severity"]) + " (" + str(cve["score"]) + " / 10) |")
    lines.append("| **Published**| " + str(cve["published"]) + " |")
    lines.append("")
    lines.append("### Description")
    lines.append("")
    lines.append(cve["description"])
    lines.append("")

    # ── References ────────────────────────────────────────────────────────────
    if cve.get("references"):
        lines.append("### References")
        lines.append("")
        for ref in cve["references"]:
            lines.append("- " + ref)
        lines.append("")

    lines.append("---")
    lines.append("")

    # ── Exploitation ──────────────────────────────────────────────────────────
    lines.append("## Exploitation")
    lines.append("")

    # Metasploit modules
    lines.append("### Metasploit")
    lines.append("")
    if recon and recon.get("metasploit"):
        lines.append("```bash")
        for mod in recon["metasploit"]:
            lines.append("use " + mod)
            lines.append("show options")
            lines.append("set RHOSTS <TARGET_IP>")
            lines.append("run")
        lines.append("```")
    else:
        lines.append("```bash")
        lines.append("# No known Metasploit module — manual exploitation required")
        lines.append("```")
    lines.append("")

    # PoC links
    lines.append("### PoC Exploits")
    lines.append("")
    if recon and recon.get("pocs"):
        for poc in recon["pocs"]:
            if "error" not in poc:
                lines.append("- [" + poc["name"] + "](" + poc["url"] + ") (" + str(poc["stars"]) + " stars)")
    else:
        lines.append("- No PoC found — check ExploitDB or search GitHub manually")
    lines.append("")

    # Manual steps — blank template for user to fill in
    lines.append("### Manual Steps")
    lines.append("")
    lines.append("```bash")
    lines.append("# Step 1 — Reconnaissance")
    lines.append("nmap -sV -p- <TARGET_IP>")
    lines.append("")
    lines.append("# Step 2 — Verify vulnerability")
    lines.append("# Add your verification command here")
    lines.append("")
    lines.append("# Step 3 — Exploit")
    lines.append("# Add your exploit command here")
    lines.append("")
    lines.append("# Step 4 — Post exploitation")
    lines.append("whoami")
    lines.append("id")
    lines.append("cat /etc/passwd")
    lines.append("```")
    lines.append("")
    lines.append("---")
    lines.append("")

    # ── Practice Resources ────────────────────────────────────────────────────
    lines.append("## Practice Resources")
    lines.append("")

    if resources and resources.get("found"):
        # TryHackMe
        if resources.get("thm"):
            lines.append("### TryHackMe")
            lines.append("")
            for room in resources["thm"]:
                free_tag = " *(Free)*" if room["free"] else " *(Subscription)*"
                lines.append("- [" + room["name"] + "](" + room["url"] + ")" + free_tag + " — " + room["difficulty"])
            lines.append("")

        # HackTheBox
        if resources.get("htb"):
            lines.append("### HackTheBox")
            lines.append("")
            for machine in resources["htb"]:
                free_tag = " *(Free)*" if machine["free"] else " *(VIP)*"
                lines.append("- [" + machine["name"] + "](" + machine["url"] + ")" + free_tag + " — " + machine["difficulty"])
            lines.append("")

        # VulnHub
        if resources.get("vulnhub"):
            lines.append("### VulnHub *(Always Free)*")
            lines.append("")
            for vm in resources["vulnhub"]:
                lines.append("- [" + vm["name"] + "](" + vm["url"] + ")")
            lines.append("")

        # ExploitDB
        if resources.get("exploitdb"):
            lines.append("### ExploitDB")
            lines.append("")
            for edb in resources["exploitdb"]:
                lines.append("- [EDB-" + edb["id"] + " — " + edb["title"] + "](" + edb["url"] + ")")
            lines.append("")

        # YouTube
        if resources.get("youtube"):
            lines.append("### YouTube Walkthroughs")
            lines.append("")
            for yt in resources["youtube"]:
                lines.append("- [" + yt["title"] + "](" + yt["url"] + ")")
            lines.append("")
    else:
        lines.append("*No curated resources found — check TryHackMe, HackTheBox, or VulnHub manually.*")
        lines.append("")

    lines.append("---")
    lines.append("")

    # ── Personal Notes ────────────────────────────────────────────────────────
    lines.append("## My Notes")
    lines.append("")
    lines.append("### What I learned")
    lines.append("")
    lines.append("*Fill this in after practicing...*")
    lines.append("")
    lines.append("### What worked")
    lines.append("")
    lines.append("*What exploit path worked for you?*")
    lines.append("")
    lines.append("### What didn't work")
    lines.append("")
    lines.append("*What failed and why?*")
    lines.append("")
    lines.append("### Flags / Proof")
    lines.append("")
    lines.append("```")
    lines.append("user.txt:  ")
    lines.append("root.txt:  ")
    lines.append("```")
    lines.append("")
    lines.append("---")
    lines.append("")
    lines.append("*Generated by [CVE Scaffolder](https://github.com/SRMOPY/project-blueprint)*")

    # ── Write to file ─────────────────────────────────────────────────────────
    with open(note_path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))

    return note_path


# ── Quick test ────────────────────────────────────────────────────────────────

if __name__ == "__main__":
    import sys
    from fetcher import fetch_cve
    from recon import run_recon
    from resources import get_resources

    cve_id = sys.argv[1] if len(sys.argv) > 1 else "CVE-2021-44228"

    print("Fetching data for " + cve_id + "...")
    cve       = fetch_cve(cve_id)
    recon     = run_recon(cve_id)
    resources = get_resources(cve_id)

    path = generate_note(cve, recon, resources)
    print("[+] Note saved to: " + path)